<?php

declare(strict_types=1);

namespace DaemsModule\Communications\Infrastructure\Renderer;

/**
 * Converts a rendered email-HTML template to a plain-text fallback for the
 * `text/plain` MIME part of multipart emails.
 *
 * Conversion rules (intentionally small set — emails generated by this module
 * use a known subset of HTML tags from the templates + CommonMark output):
 *
 *   - `<a href="URL">text</a>`         → `text (URL)` (URL omitted when same as text)
 *   - `<br>` / `<br/>`                 → single newline
 *   - `<li>...</li>`                   → `- ...` line (in `<ol>` blocks: `1. `, `2. `, …)
 *   - `<p>`, `<div>`, `<h1>`-`<h6>`,
 *     `<tr>`, `<table>`, `<blockquote>`→ block boundary (double newline)
 *   - `<strong>`, `<em>`, `<b>`, `<i>` → unwrap (text preserved)
 *   - All other tags                   → stripped
 *   - HTML entities                    → decoded (UTF-8)
 *   - Excess whitespace                → collapsed; runs of >2 blank lines
 *     collapsed to exactly one blank line.
 *
 * Anything inside `<style>`, `<script>`, `<head>` is removed entirely.
 */
final class Html2Text
{
    public function convert(string $html): string
    {
        // 1. Strip head / style / script blocks entirely.
        $html = (string) preg_replace('#<(head|style|script)\b[^>]*>.*?</\1>#is', '', $html);

        // 2. Normalise self-closing and break tags to a sentinel newline marker
        //    we can resurrect at the end (avoids tag-strip swallowing them).
        $html = (string) preg_replace('#<br\s*/?\s*>#i', "\n", $html);

        // 3. Convert links to "text (URL)" form.
        $html = (string) preg_replace_callback(
            '#<a\b[^>]*\bhref\s*=\s*["\']([^"\']+)["\'][^>]*>(.*?)</a>#is',
            static function (array $m): string {
                $href = trim($m[1]);
                $text = trim(strip_tags($m[2]));
                if ($text === '' || $text === $href) {
                    return $href;
                }
                return $text . ' (' . $href . ')';
            },
            $html,
        );

        // 4. Convert <ol> blocks BEFORE <ul> (so numbering works per-list).
        $html = (string) preg_replace_callback(
            '#<ol\b[^>]*>(.*?)</ol>#is',
            static function (array $m): string {
                $i = 0;
                $items = (string) preg_replace_callback(
                    '#<li\b[^>]*>(.*?)</li>#is',
                    static function (array $im) use (&$i): string {
                        $i++;
                        return "\n" . $i . '. ' . trim(strip_tags($im[1]));
                    },
                    $m[1],
                );
                return "\n" . $items . "\n";
            },
            $html,
        );

        // 5. Convert <ul> bullets.
        $html = (string) preg_replace_callback(
            '#<ul\b[^>]*>(.*?)</ul>#is',
            static function (array $m): string {
                $items = (string) preg_replace(
                    '#<li\b[^>]*>(.*?)</li>#is',
                    "\n- $1",
                    $m[1],
                );
                return "\n" . $items . "\n";
            },
            $html,
        );

        // 6. Stray <li> outside ul/ol → bullet.
        $html = (string) preg_replace('#<li\b[^>]*>(.*?)</li>#is', "\n- $1", $html);

        // 7. Block-level closers → double newline. Order matters (specific first).
        $blockClosers = ['p', 'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
                         'tr', 'table', 'blockquote', 'section', 'article', 'header', 'footer'];
        foreach ($blockClosers as $tag) {
            $html = (string) preg_replace('#</' . $tag . '\s*>#i', "\n\n", $html);
        }

        // 8. Strip all remaining tags.
        $text = strip_tags($html);

        // 9. Decode HTML entities (UTF-8).
        $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');

        // 10. Whitespace normalisation:
        //   a) trim per line, b) collapse runs of blank lines.
        $lines = preg_split('/\r?\n/', $text);
        if ($lines === false) {
            $lines = [$text];
        }
        $lines = array_map(static fn(string $line): string => rtrim(preg_replace('/[ \t]+/', ' ', $line) ?? $line), $lines);

        $collapsed = [];
        $blankRun = 0;
        foreach ($lines as $line) {
            if (trim($line) === '') {
                $blankRun++;
                if ($blankRun <= 1) {
                    $collapsed[] = '';
                }
            } else {
                $blankRun = 0;
                $collapsed[] = $line;
            }
        }

        return trim(implode("\n", $collapsed));
    }
}
